import SwiftUI

/// The printable A4 page content for the "Glucose Distribution" PDF export.
/// Reuses the same chart/stat components shown in the on-screen Statistics sheet so the
/// exported report visually matches the app, but forces light, print-friendly styling.
struct StatPDFReportView: View {
    let reportName: String
    let rangeDisplayName: String
    let periodStart: Date
    let periodEnd: Date
    let generatedAt: Date

    let glucose: [GlucoseStored]
    let glucoseRangeStats: [GlucoseRangeStats]
    let highLimit: Decimal
    let lowLimit: Decimal
    let units: GlucoseUnits
    let eA1cDisplayUnit: EstimatedA1cDisplayUnit
    let timeInRangeType: TimeInRangeType

    private let margin: CGFloat = 32

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            header

            Divider()

            GlucoseDistributionChart(
                glucose: glucose,
                highLimit: highLimit,
                lowLimit: lowLimit,
                units: units,
                glucoseRangeStats: glucoseRangeStats,
                timeInRangeType: timeInRangeType
            )

            Divider()

            VStack(spacing: 16) {
                GlucoseSectorChart(
                    highLimit: highLimit,
                    units: units,
                    glucose: glucose,
                    timeInRangeType: timeInRangeType,
                    showChart: true
                )

                Divider()

                GlucoseMetricsView(
                    units: units,
                    eA1cDisplayUnit: eA1cDisplayUnit,
                    glucose: glucose
                )
            }

            Spacer(minLength: 0)

            footer
        }
        .padding(margin)
        .frame(width: StatPDFExporter.pageSize.width, height: StatPDFExporter.pageSize.height, alignment: .topLeading)
        .background(Color.white)
        .foregroundStyle(Color.black)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Trio — Statistics Report")
                .font(.title2)
                .fontWeight(.bold)

            if !reportName.isEmpty {
                Text(reportName)
                    .font(.headline)
            }

            Text("Glucose · \(rangeDisplayName) (\(dateRangeText))")
                .font(.subheadline)
                .foregroundStyle(Color.secondary)

            Text("Generated \(generatedAt.formatted(date: .abbreviated, time: .shortened))")
                .font(.caption)
                .foregroundStyle(Color.secondary)
        }
    }

    private var footer: some View {
        Text("Generated by Trio")
            .font(.caption2)
            .foregroundStyle(Color.secondary)
            .frame(maxWidth: .infinity, alignment: .center)
    }

    private var dateRangeText: String {
        "\(periodStart.formatted(date: .abbreviated, time: .omitted)) – \(periodEnd.formatted(date: .abbreviated, time: .omitted))"
    }
}
